// <auto-generated />
using System;
using ExamPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamPortalAPI.Migrations
{
    [DbContext(typeof(ExamPortalDBContext))]
    [Migration("20230630144332_Initial Migration2")]
    partial class InitialMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamPortal.Models.Domain.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("ExamPortal.Models.Domain.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<int>("Category_Id")
                        .HasColumnType("int");

                    b.Property<string>("ExamDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamDuration")
                        .HasColumnType("int");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExamPassPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ExamTotalQuestion")
                        .HasColumnType("int");

                    b.Property<decimal>("QuestionMark")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExamId");

                    b.ToTable("exams");
                });

            modelBuilder.Entity("ExamPortal.Models.Domain.ExamImages", b =>
                {
                    b.Property<string>("exam_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("examImages");
                });

            modelBuilder.Entity("ExamPortal.Models.Domain.Questions", b =>
                {
                    b.Property<int>("question_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("question_id"));

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<int>("correctAnswer")
                        .HasColumnType("int");

                    b.Property<int>("exam_id")
                        .HasColumnType("int");

                    b.Property<string>("option_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("option_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("option_3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("option_4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("question_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("question_id");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("ExamPortal.Models.Domain.UserExamData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("answer")
                        .HasColumnType("int");

                    b.Property<DateTime>("attemptedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<int>("exam_id")
                        .HasColumnType("int");

                    b.Property<int>("question_id")
                        .HasColumnType("int");

                    b.Property<int>("testId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("userExamDatas");
                });

            modelBuilder.Entity("ExamPortal.Models.Domain.UserResults", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Attempted_Questions")
                        .HasColumnType("int");

                    b.Property<int>("Category_Id")
                        .HasColumnType("int");

                    b.Property<int>("Correct_Answers")
                        .HasColumnType("int");

                    b.Property<int>("Exam_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Exam_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NotAttempted_Questions")
                        .HasColumnType("int");

                    b.Property<bool>("Pass_Flag")
                        .HasColumnType("bit");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_MarksObtained")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Wrong_Answers")
                        .HasColumnType("int");

                    b.Property<int>("examTotalQuestions")
                        .HasColumnType("int");

                    b.Property<decimal>("passPercentageRequired")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ResultId");

                    b.ToTable("userResults");
                });
#pragma warning restore 612, 618
        }
    }
}
